---
title: "Many small models -- the Secret Weapon"
description: |
  how to fit and visualize small multiples
author:
  - name: Allen and Andrew
    url: {}
date: 2022-06-10
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
substrate <- c("soil", "onion", "radish", "broccoli", "soy", "corn")

genotypes <- c("H", "N")

library(tidyverse)


treatment <- expand_grid(substrate, genotypes)


fly_ids <- paste0("fly", 1:(30*12))

# assign flies to treatments

trt_id <- rep(1:12, times = 30)

design_matrix <- tibble(fly_ids, trt_id) |> 
  rowwise() |> 
  mutate(trt = list(treatment[trt_id,])) |> 
  unnest("trt")

obs_flies <- design_matrix |> 
  rowwise() |> 
  mutate(time = list(c("t1", "t2", "t3"))) |> 
  unnest(time) |> 
  mutate(obs = rnorm(length(fly_ids), mean = 40, sd = sqrt(40)))

# faster simpler 
expand_grid(genotype = c("H", "N"),
            substrate = c("control", "onion", "radish", "broco", "soy", "corn"),
            flies = 1:30,
            time = c("4", "24", "48")) %>%
  group_by(genotype, substrate) %>%
  mutate(fly_id = cur_group_id()) %>%
  ungroup()



```


Fit many small models to each one!

```{r}
fly_model_df <- obs_flies |> 
  mutate(time = factor(time, levels = c("t3", "t1", "t2"))) |> 
  nest_by(substrate, genotypes, .key = "flydata")

fly_model_coefs <- fly_model_df |> 
  # fit models
  mutate(model = list(lm(obs ~ time, data = flydata))) |> 
  # mutate(coef = list(coef(model))) # there's a cooler way! 
  mutate(tb = list(broom::tidy(model))) |> 
  unnest(cols = c("tb"))

fly_model_coefs |> 
  filter(term == "(Intercept)") |> 
  ggplot(aes(y = estimate, x = substrate, col = genotypes, ymin = estimate - std.error, ymax = estimate + std.error)) + 
  geom_pointrange(position = position_dodge(width = .1))

```


could do it again for another kind of preference: the contrast between t1 and t3

```{r}
fly_model_coefs |> 
  filter(term == "timet1") |> 
  ggplot(aes(y = estimate, x = substrate, col = genotypes, 
             ymin = estimate - std.error, ymax = estimate + std.error)) + 
  geom_pointrange(position = position_dodge(width = .1))
```

what about for a zero-inflated model?

```{r}
library(glmmTMB)

obs_flies_zi <- obs_flies |> 
  mutate(time = factor(time, levels = c("t3", "t1", "t2")),
         obs = if_else(runif(1080)<.1, true = 0, false = obs)) 


obs_flies_zi |> 
  nest_by(substrate, genotypes, .key = "flydata") |> 
  mutate(zi_mod = list(glmmTMB(obs ~ time, ziformula = ~time, data = flydata)))


```


From easystats [documentation](https://easystats.github.io/parameters/reference/simulate_parameters.html)

```{r}

library(parameters)
model <- glmmTMB(
  count ~ spp + mined + (1 | site),
  ziformula = ~mined,
  family = poisson(),
  data = Salamanders
)

simulate_parameters(model, centrality = "mean")
simulate_parameters(model, ci = c(.8, .95), component = "zero_inflated")
```


### bootstrapping a dataframe

```{r}
one_sample <- obs_flies_zi |> 
  nest(timeobs = c(time, obs)) |> 
  # group by experimental factors
  group_by(substrate, genotypes) |> 
  sample_frac(size = 1, replace = TRUE)

one_sample |> 
  filter(trt_id == 1) |> 
  arrange(fly_ids)

one_sample |> 
  unnest(timeobs) |> 
  ungroup()

```

that's one rep, let's do a lot! 

```{r}
boot_list <- rerun(30, {
  obs_flies_zi |> 
    nest(timeobs = c(time, obs)) |> 
    # group by experimental factors
    group_by(substrate, genotypes) |> 
    sample_frac(size = 1, replace = TRUE) |> 
    unnest(timeobs) |> 
    ungroup()
})
```

now just use `map` to apply a function to each of these

```{r}
model_list <- boot_list |> 
  map(~ glmmTMB(obs ~ time, ziformula = ~time, data = .x))

# use bootstrapped models to predict on original dataset
model_predictions <- map(model_list, 
                         predict,
                         type = "response",
                         newdata = obs_flies_zi)

# model_predictions |> map(head)

# rowMeans(do.call(cbind, model_predictions))

# get more information though!
boot_pred_df <- model_predictions |> 
  map_dfr(enframe, name = "rownum", value = "pred", .id = "boot_id")

```

summarize each of these

```{r}
summarized_data <- boot_pred_df |> 
  nest_by(rownum) |> 
  mutate(med = median(data$pred),
         quant_lo = quantile(data$pred, 0.025),
         quant_hi = quantile(data$pred, 0.975)) |> 
  select(-data)

bind_cols(obs_flies_zi, summarized_data) |> 
  ggplot(aes(x = substrate, y = obs)) + 
  geom_count() + 
  facet_grid(genotypes ~ time) + 
  geom_count(aes(y = med, x = substrate), col = "orange") + 
  geom_pointrange(aes(y = med, ymin = quant_lo, ymax = quant_hi), col = "green")

```

