---
title: "Poisson regression"
description: |
  A short description of the post.
author:
  - name: Vincent B  and Andrew
    url: {}
date: 2022-06-23
output:
  distill::distill_article:
    self_contained: false
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Poisson regression 

$$
\begin{align}
y &\sim \text{Poisson}(\lambda) \\
log(\lambda) &= \alpha + \beta x
\end{align}

$$

What are these? 

counting limpets on quadrats

tidal height is the predictor

```{r}

tide <- runif(40, -3, 1)

hist(tide)

```


0 is sea level

At sea level, how many limpets on average

```{r}
avg_limpet <- log(30)
exp(avg_limpet)

```

for every 1m change in tide, how do limpts change?

```{r}
change_limpet <- log(.9)
```

about 10% less for every m

```{r}
library(tidyverse)

fake_limp_avg <- tibble(tide,
       log_average = avg_limpet + change_limpet*tide,
       count_average = exp(log_average))

fake_limp_avg |> 
  ggplot(aes(x = tide, y = count_average)) + geom_point()
```



okay now make fake observations

```{r}

set.seed(1234)

limpet_obs <- fake_limp_avg |> 
  mutate(obs_limpets = rpois(nrow(fake_limp_avg), count_average))

limpet_obs |> 
  ggplot(aes(x = tide, y = count_average)) + #geom_point() + 
  geom_point(aes(y = obs_limpets), col = "red", size = 3)
```


```{r}
library(brms)

limpet_count_model <- brm(obs_limpets ~ tide,
                          data = limpet_obs,
                          file = here::here("_posts/2022-06-23-poisson-regression/", "limpet_count_model.rds"),
                          file_refit = "on_change",
                          family = poisson(link = "log"))
```

```{r}
# shinystan::launch_shinystan(limpet_count_model)
```



```{r}
library(tidybayes)

tidy_draws(limpet_count_model) |> 
  ggplot(aes(x = b_tide)) + 
  stat_halfeye()


```


```{r}

tidy_draws(limpet_count_model) |> 
  ggplot(aes(x = b_tide)) + 
  stat_halfeye() + 
  geom_vline(xintercept = change_limpet)

```

```{r}
handmade_predictions <- tidy_draws(limpet_count_model) |> 
  rowwise() |> 
  mutate(dataset = list(limpet_obs),
         pred_limp = list(b_Intercept + b_tide * dataset$tide)) |> 
  unnest(cols = c("dataset", "pred_limp"))


handmade_predictions |> 
  ggplot(aes(x = tide, y = exp(pred_limp))) + 
  stat_lineribbon()


```

```{r}
as.matrix(limpet_count_model)
```



```{r}
limpet_obs |> 
  add_predicted_draws(limpet_count_model)
```


```{r}
limpet_obs |> 
  add_predicted_rvars(limpet_count_model)
```


